[tool.poetry]
name = "hello-robot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
robotframework = "^6.1.1"
package_mode = false


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
